#!/bin/sh
dotnet publish ./YtPlaylist.csproj -c Release -o ./out/linux-x64 -r linux-x64 /p:UseAppHost=true
dotnet publish ./YtPlaylist.csproj -c Release -o ./out/win-x64 -r win-x64 /p:UseAppHost=true /p:DefineConstants=WIN

mv ./out/linux-x64/ytsync ./out/ytsync-linux-x64
rm -r ./out/linux-x64

mv ./out/win-x64/ytsync.exe ./out/ytsync-win-x64.exe
rm -r ./out/win-x64
